version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout

      # Instalamos dependencias
      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run Tests / Linting
          command: |
            if npm run | grep -q test; then
              npm run test
            else
              echo No se encontró un script de test en package.json
            fi
      
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: cimg/node:current
    steps:
      # Recuperamos los archivos del paso anterior (ahorramos tiempo de checkout e install)
      - attach_workspace:
          at: .
      - run:
          name: Install Vercel CLI
          command: sudo npm install -g vercel
      - run:
          name: Deploy to Vercel
          command: |
            echo "Desplegando.."
            vercel pull --yes --environment=production --token=$VERCEL_TOKEN
            vercel build --prod --token=$VERCEL_TOKEN
            vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
