version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      # Instalamos dependencias
      - run:
          name: Install dependencies
          command: npm install
      # Ejecutamos tests (descomenta si ya tienes un script de test configurado)
      - run:
          name: Run Tests / Linting
          command: |
            if npm run | grep -q test; then
              npm run test
            else
              echo No se encontró un script de test en package.json. Saltando...
            fi
      # Persistimos el directorio de trabajo para que el job de deploy tenga acceso a los archivos
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: cimg/node:current # Usamos Node también aquí para tener soporte nativo de npm
    steps:
      # Recuperamos los archivos del paso anterior (ahorramos tiempo de checkout e install)
      - attach_workspace:
          at: .
      - run:
          name: Install Vercel CLI
          command: sudo npm install -g vercel
      - run:
          name: Deploy to Vercel
          command: |
            if [  = main ]; then
              echo Desplegando en Producción...
              vercel deploy --prod --token= --yes
            else
              echo Desplegando Preview para la rama ...
              vercel deploy --token= --yes
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # Quitamos el filtro 'only: main' para que las ramas secundarias 
          # también se desplieguen como 'Previews' de Vercel. 
          # La lógica dentro del job de deploy sabrá si es producción o no.
